name: wordle_examples

environment:
    sdk: ">=2.12.0 <3.0.0"

dependencies:
    wordle: any

dependency_overrides:
    wordle:
        path: ..

dev_dependencies:
    build_runner: ^2.1.11
    build_web_compilers: ^3.2.3
